// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto2";

package extensions.fuzzing.extension_frame_host.proto;

import "extensions/common/mojom/frame.mojom.mojolpm.proto";

message NewLocalFrameHostAction {
  required uint32 id = 1;
}

message RunUntilIdleAction {}

message Action {
  oneof action {
    NewLocalFrameHostAction new_local_frame_host = 1;
    RunUntilIdleAction run_until_idle = 2;
    mojolpm.extensions.mojom.LocalFrameHost.AssociatedRemoteAction
        local_frame_host_associated_remote_action = 3;
  }
}

message Sequence {
  repeated uint32 action_indexes = 1 [packed = true];
}

message Testcase {
  repeated Action actions = 1;
  repeated Sequence sequences = 2;
  repeated uint32 sequence_indexes = 3 [packed = true];
}
