// Copyright 2026 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

syntax = "proto2";

package content.fuzzing.background_fetch_service.proto;

import "third_party/blink/public/mojom/background_fetch/background_fetch.mojom.mojolpm.proto";

message RunUntilIdleAction {}

message Action {
  oneof action {
    RunUntilIdleAction run_until_idle = 1;
    mojolpm.blink.mojom.BackgroundFetchService.RemoteAction
        background_fetch_service_remote_action = 2;
    mojolpm.blink.mojom.BackgroundFetchRegistrationService.RemoteAction
        background_fetch_registration_service_remote_action = 3;
  }
}

message Sequence {
  repeated uint32 action_indexes = 1 [packed = true];
}

message Testcase {
  repeated Action actions = 1;
  repeated Sequence sequences = 2;
  repeated uint32 sequence_indexes = 3 [packed = true];
}
